version: "3.8"
services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - ./.local/data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1